# Generated by Django 5.2.8 on 2025-11-10 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(help_text='Separate multiple authors with commas', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('isbn10', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('pages', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tags', models.CharField(blank=True, help_text='Separate tags with commas', max_length=500)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_cover_path/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('reading_status', models.CharField(choices=[('unread', 'Unread'), ('reading', 'Currently Reading'), ('completed', 'Completed'), ('wishlist', 'Wishlist')], default='unread', max_length=20)),
                ('rating', models.IntegerField(blank=True, help_text='Rate from 1 to 5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
